version: '3.8'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/:/docker-entrypoint-initdb.d/
  cache:
    image: redis:7.0.2-alpine
    container_name: news-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  api:
    container_name: news-api
    build:
      context: .
    depends_on:
      - db
      - cache
    ports:
      - 3301:3300
    env_file:
      - ".env"
    links:
      - db
      - cache
    volumes:
      - ./:/app
#      - type: bind
#        source: .
#        target: /app

volumes:
  db:
    driver: local
  cache:
    driver: local
